poke/urls.py
from django.urls import path
from . import views

app_name = 'poke'

urlpatterns = [
    path('pokemon/', views.pokepost, name='pokepost'),
    path('pokemon/<int:pk>/', views.PokeDetailView.as_view(), name='index'),
    path('pokemon/pokepost/<int:pk>/', views.pokepost, name='pokepost'),
    
    path('moves/', views.movepost, name='movepost'),
    path('moves/<int:pk>', views.MoveDetailView.as_view(), name='moves'),
    path('moves/movepost/<int:pk>/', views.movepost, name='movepost'),

    path('pokemon/pgl/', views.pgl, name='pgl'),
]

pokemon/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('poke.urls'), name='poke'),
]

templates/blind.html
{% load staticfiles %}
{% if e %}
	{% if f %}
	<div class="col-md-6">
		{% if blind %}
		<p>盲点</p>
		{% for t in blind %}
			<h4><span class="label label-default" style="background-color: {{t.color}}">{{t.name}}</span></h4>
		{% endfor %}
		{% else %}
			<p>无盲点</p>
		{% endif %}
	</div>
	<div class="col-md-6">
		{% if twice %}
		<p>2倍</p>
		{% for t in twice %}
			<h4><span class="label label-default" style="background-color: {{t.color}}">{{t.name}}</span></h4>
		{% endfor %}
		{% else %}
			<p>无2倍</p>
		{% endif %}
	</div>
	{% else %}
	<p>请选择非变化技能</p>
	{% endif %}
{% else %}
	<p>请至少选择一个技能</p>
{% endif %}




templates/load.html
{% for poke in ranklist %}
<div class="img-wrap">
	<div class="img-wrap1"><p><span class="label label-danger">{{poke.rank}}</span>&nbsp;&nbsp;<b>{{poke.name}}</b></p></div>
	<div class="img-wrap2">
		<a id="{{id}}" data="{{poke.id}}" name="{{poke.name}}" href="#type-chart" role="button" data-toggle="modal">
			<img src="/static/poke/img/pgl/{{poke.id}}.png" class="img-thumbnail">
		</a>
	</div>
</div>
{% endfor %}

templates/moves.html
{% load staticfiles %}
{% load move_tags %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Pokemon-Moves</title>

    <!-- Bootstrap -->

    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'poke/css/select2.css' %}" rel="stylesheet">
    <link href="{% static 'poke/css/bootstrap-slider.css' %}" rel="stylesheet" /> <!-- 滑动条 -->
    <link href="{% static 'poke/css/font-awesome.min.css' %}" rel="stylesheet" />
    <link href="{% static 'poke/css/my.css' %}" rel="stylesheet"> <!-- 后面覆盖前面 -->

  </head> 
  <body>
  	<div class="container">

		<div class="row clearfix"><h3><b>{{move.name}}</b>&emsp;&emsp;<a href="{% url 'poke:pokepost' %}" target="_blank">首页</a>&emsp;&emsp;<a href="{% url 'poke:pgl' %}" target="_blank">pgl-rank</a></h3></div>
		<hr />

		<div class="row clearfix">
			<table class="table table-condensed">
				<thead>
				    <tr>
				      <th></th>
				      <th>招式</th>
				      <th></th>
				      <th>属性</th>
				      <th>类型</th>
				      <th>威力</th>
				      <th>z</th>
				      <th>命中</th>
				      <th>先制</th>
				      <th>说明</th>
				      <th>神百</th>
				    </tr>
				</thead>
				<tbody>
				    <tr>
				      <td style="width:10px;"><a href="{% url 'poke:moves' move_prev.id %}" role="button" class="btn"><<</a></td>
				      <td>
				      	<form id="movesform" class="bs-example bs-example-form" role="form" action="{% url 'poke:movepost' move.id %}" method="post">
							{% csrf_token %}
							<select onchange="submitForm();" name="movepost" id="moveselect" style="width:110px">
								{% get_moves as moves %}
								{% for m in moves %}
								<option value="{{m.id}}">{{m.name}}</option>
								{% endfor %}
							</select>
						</form>
				      </td>
				      <td style="width:10px;"><a href="{% url 'poke:moves' move_next.id %}" role="button" class="btn">>></a></td>
				      <td><h4><span id="types" class="label label-default" style="width:60px; background-color:{{move.types.color}};">{{move.types.name}}</span></h4></td>
				      <td><h4><span id="cate" class="label label-default" style="width:60px; background-color:{{move.cate.color}};">{{move.cate.name}}</span></h4></td>
				      <td id="power" style="width:60px;">{{move.power}}</td>
				      <td id="z_power" style="width:60px;">{{move.z_power}}</td>
				      <td id="accuracy" style="width:60px;">{{move.accuracy}}</td>
				      <td id="priority" style="width:60px;">{{move.priority}}</td>
				      <td id="detail" style="width:700px;">{{move.detail}}</td>
				      <td  style="width:60px;"><a href="https://wiki.52poke.com/wiki/{{move.name}}" id="link" target="_blank">详情</a></td>
				    </tr>
				</tbody>
			</table>
		</div>
		<hr />
		<div class="row clearfix">
			{% for p in move.id|get_detail %}
			<p>{{p}}</p>
			{% endfor %}
		</div>
		<hr />
		<div class="row clearfix">

			<div class="col-md-1"><b>作用范围</b></div>
			<div class="col-md-4">{{move.move_range.name}}</div>
			<div class="col-md-4">
				<div class="row">
					<div class="btn-group">
		              <button type="button" class="btn btn-default" style="background-color: {{move.move_range.d1}};">对手</button>
		              <button type="button" class="btn btn-default" style="background-color: {{move.move_range.d2}};">对手</button>
		              <button type="button" class="btn btn-default" style="background-color: {{move.move_range.d3}};">对手</button>
		            </div>
		        </div>
		        <div class="row">
		            <div class="btn-group">
		              <button type="button" class="btn btn-default" style="background-color: {{move.move_range.z}};">自身</button>
		              <button type="button" class="btn btn-default" style="background-color: {{move.move_range.t1}};">同伴</button>
		              <button type="button" class="btn btn-default" style="background-color: {{move.move_range.t2}};">同伴</button>
		            </div>
	            </div>
			</div>
			<div class="col-md-2">
				<div class="panel panel-default">  
		  			<div class="panel-body">  
		  				<div class="row">
		  					<div class="col-md-4">
								<button id="b1" class="btn btn-default btn-sm" type="button" value="{{move.types.name}},{{move.cate.name}}">计算</button>
		  					</div>
		  				</div>
		  				<hr />
		  				<div class="row" id="display"></div>
				  	</div>  
				</div>
			</div>
		</div>
	</div><!-- container -->

		  	

	

	<!-- JavaScript 放置在文档最后面可以使页面加载速度更快 -->
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在其他js前边) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'poke/js/ajax.js' %}"></script>
    <!-- <script src="{% static 'poke/js/bootstrap-slider.min.js' %}"></script> -->
    <script src="{% static 'poke/js/select2.js' %}"></script>
    <script type="text/javascript">

		$(function(){ 
	        	$("#moveselect option[value='{{move.id}}']").attr("selected","selected");
	        	$("#moveselect").select2();
	      	});

		function submitForm(){var form = document.getElementById("movesform");form.submit();};

		// 计算技能
    	$("#b1").click(function(){
    		$.ajax({
			    url: "{% url 'poke:movepost' %}",
			    data: { s1: [$(this).val().split(',')[0], $(this).val().split(',')[1]],
					},
			    type: "POST",
			    success: function(data) { 
			    	$('#display').html(data);
			    } 
			});
		});
    </script>

  </body>
</html>

templates/pgl_rank.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Pokemon-PGL</title>

    <!-- Bootstrap -->

    <link href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'poke/css/select2.css' %}" rel="stylesheet">
    <link href="{% static 'poke/css/bootstrap-slider.css' %}" rel="stylesheet" /> <!-- 滑动条 -->
    <link href="{% static 'poke/css/font-awesome.min.css' %}" rel="stylesheet" />
    <link href="{% static 'poke/css/my.css' %}" rel="stylesheet"> <!-- 后面覆盖前面 -->

  </head> 
  <body>
  	<div class="container">

  		<div class="modal" id="type-chart" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"> <!-- 遮罩窗 -->
          
		  </div><!-- 遮罩窗 -->

  		<div class="row clearfix"><h4><a href="{% url 'poke:pokepost' %}" target="_blank">首页</a>&emsp;<a href="https://3ds.pokemon-gl.com/" target="_blank">PGL</a>&emsp;<a href="{% url 'poke:movepost' %}" target="_blank">Moves</a></h4></div>
  		<div class="row clearfix">
        <div class="col-md-7">
    			<form id="seasonform" class="bs-example bs-example-form" role="form" action="{% url 'poke:pgl' %}" method="get">
  	  			<select  onchange="submitForm();" id="season" style="height: 25px" name="season">
              <option value="317" id='317'>
                Season 17　09/03/19 09:00 AM - 11/26/19 08:59 AM JST　09/03/19 12:00 AM - 11/25/19 11:59 PM UTC
              </option>
              <option value="315" id='315'>
                Season 15　04/02/19 09:00 AM - 06/18/19 08:59 AM JST　04/02/19 12:00 AM - 06/17/19 11:59 PM UTC
              </option>
              <option value="313" id='313'>
                Season 13　11/06/18 09:00 AM - 01/08/19 08:59 AM JST　11/06/18 12:00 AM - 01/07/19 11:59 PM UTC
              </option>
              <option value="311" id='311'>
                Season 11　07/10/18 09:00 AM - 09/04/18 08:59 AM JST　07/10/18 12:00 AM - 09/03/18 11:59 PM UTC
              </option>
  	  			</select>
  	  		</form>
        </div>
        <div class="col-md-3">更新时间：{{updateDate}}</div>
        <div class="col-md-1"></div>
        <div class="col-md-1" id="update">
          {% if is_updated %}
            <p style="color:red;">有更新！</p>
          {% endif %}
        </div>
  		</div>

  		<hr />
  		
		<div class="row clearfix">
			<div class="col-md-12 column" id='main-season'>
        <p><b>说明: {{detail}}</b></p>
				{% block season %}
				{% endblock season %}
			</div>
		</div>

	</div><!-- container -->

		  	

	

	<!-- JavaScript 放置在文档最后面可以使页面加载速度更快 -->
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在其他js前边) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{% static 'poke/js/ajax.js' %}"></script>
    <!-- <script src="{% static 'poke/js/bootstrap-slider.min.js' %}"></script> -->
    <script src="{% static 'poke/js/select2.js' %}"></script>
    <script type="text/javascript">
      

      

      $(function(){ 
          $("#season option[value={{seasonid}}]").attr("selected","selected");
          $('#season').select2();
      });
      

    	function submitForm(){var form = document.getElementById("seasonform");form.submit();};

		   // 对于动态加载页面, on方法要先找到原选择器, 再找到动态添加的选择器

	    $("#type-chart").on("mouseover",".tr", function(){ //鼠标悬停
	    	$('#name').text($(this).children('td').eq(1).text());
        $('#t1').text($(this).attr('name').split(',')[0]);
        $('#t2').text($(this).attr('name').split(',')[1]);
        $('#t1').css("background-color",$(this).attr('name').split(',')[5]);
        $('#t2').css("background-color",$(this).attr('name').split(',')[6]);
        $('#t3').text($(this).attr('name').split(',')[2]);
        $('#t4').text($(this).attr('name').split(',')[3]);
        $('#t5').text($(this).attr('name').split(',')[4]);
        $('#detail').text($(this).attr('title'));
	    });

      $("#type-chart").on("mouseover",".panel-heading a", function(){ //鼠标悬停手风琴切换
        $(this).click();
      });

      $(".tab-content").on("click", "a", function(){ //点击页面上的pokemon，对于js加载的pokemon也有效
        $.ajax({
          url: "{% url 'poke:pgl' %}",
          data: {id: $(this).attr('data'),
              seasonid: {{seasonid}},
              typeid: $(this).attr('id'),
              },
          type: "POST",
          success: function(data){
            $('#type-chart').html(data).find('select').select2();
          }
        });
      });


      $("#type-chart").on("click", '#season-change button', function(){ //切换season
          $.ajax({
          url: "{% url 'poke:pgl' %}",
          data: {id: $('h3').attr('id').split(',')[0],
              seasonid: $(this).attr('id'),
              typeid: $('h3').attr('id').split(',')[1],
              },
          type: "POST",
          success: function(data){
            $('#type-chart').html(data).find('select').select2();
          }
        });
      })

      $("#type-chart").on("click", '#type-change button', function(){ //切换对战模式
          $.ajax({
          url: "{% url 'poke:pgl' %}",
          data: {id: $('h3').attr('id').split(',')[0],
              seasonid: $('h3').attr('id').split(',')[2],
              typeid: $(this).attr('id'),
              },
          type: "POST",
          success: function(data){
            $('#type-chart').html(data).find('select').select2();
          }
        });
      })

      
      $("#type-chart").on("change", "#pokeselect", function(){ //精灵选择框
        var poke_id = $(this).val().split(',')[0];
        $.ajax({
          url: "{% url 'poke:pgl' %}",
          data: {id: $(this).val().split(',')[0],
              seasonid: $(this).val().split(',')[2],
              typeid: $(this).val().split(',')[1],
              },
          type: "POST",
          success: function(data){

            $('#type-chart').html(data).find('select').select2();
            
          }
        });
      });

      $("#type-chart").on("click", ".prevnext button", function(){ //上一个下一个pokemon
        $.ajax({
          url: "{% url 'poke:pgl' %}",
          data: {id: $(this).attr('id').split(',')[0],
              seasonid: $(this).attr('id').split(',')[2],
              typeid: $(this).attr('id').split(',')[1],
              },
          type: "POST",
          success: function(data){
            $('#type-chart').html(data).find('select').select2();
          }
        });
      });

      $(".tab-content button").click(function(){ //加载更多排名
        var a = $(this).attr('id');
        $.ajax({
          url: "{% url 'poke:pgl' %}",
          data: {load: true,
                id: $(this).attr('id'),
                seasonid: {{seasonid}},
              },
          type: "POST",
          success: function(data){
            $("#pane-"+a).html(data)
          }
        });
      });


    </script>

  </body>
</html>

templates/pokedetail.html
{% load staticfiles %}

<div class="modal-dialog" style="width:1000px; top: 50px;">
	<div class="modal-content">
		<div class="modal-header">
			<div class="col-md-4 btn-group" id="type-change">
				<button type="button" class="btn btn-default btn-success {% ifequal typeid '1' %}active{% endifequal %}" id="1">Single</button>
				<button type="button" class="btn btn-default btn-warning {% ifequal typeid '2' %}active{% endifequal %}" id="2">Double</button>
  				<button type="button" class="btn btn-default btn-info {% ifequal typeid '5' %}active{% endifequal %}" id="5">Special</button>
				<button type="button" class="btn btn-default btn-danger {% ifequal typeid '6' %}active{% endifequal %}" id="6">Wcs</button>
			</div>
			<div class="col-md-3"></div>
			<div class="col-md-5 btn-group" id="season-change">
				<button type="button" class="btn btn-default {% ifequal seasonid '317' %}active{% endifequal %}" id="317">Season 17</button>
				<button type="button" class="btn btn-default {% ifequal seasonid '315' %}active{% endifequal %}" id="315">Season 15</button>
				<button type="button" class="btn btn-default {% ifequal seasonid '313' %}active{% endifequal %}" id="313">Season 13</button>
				<button type="button" class="btn btn-default {% ifequal seasonid '311' %}active{% endifequal %}" id="311">Season 11</button>
				<!-- <button type="button" class="close" data-dismiss="modal" aria-hidden="true">X</button> -->
			</div>
		</div>
		<div id="modal-body" class="modal-body">
			
			<div class="row clearfix">
				<div class="col-md-4 column">
					
			 		<div class="btn btn-primary btn-block" style="margin:auto; ">——— <b>{{s}}</b> —— <b>{{type_}}</b> ———</div>
			 		
					<div class="panel-group" id="panel-1">
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title" data-toggle="collapse" data-parent="#panel-1" href="#panel-element-1"><b>Moves</b></a>
							</div> 
							<div id="panel-element-1" class="panel-collapse collapse in">
								<div class="panel-body">
									<table class="table-hover table-striped">
										<tbody>
											{% for key, v in move_dict.items %}
											<tr class="tr" name="{{v.model.types.name}},{{v.model.cate.name}},{{v.model.power}},{{v.model.accuracy}},{{v.model.priority}},{{v.model.types.color}},{{v.model.cate.color}}" title="{{v.model.detail}}">
												<td class="rank">{{key}}</td>
												<td class="name">{{v.name}}</td>
												<td class="ratio">{{v.usageRate|floatformat:-1}}%</td>
											</tr>
											{% empty %}
												There is no data to display
											{% endfor %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title" data-toggle="collapse" data-parent="#panel-1" href="#panel-element-2"><b>Ability</b></a>
							</div>
							<div id="panel-element-2" class="panel-collapse collapse">
								<div class="panel-body">
									<table class="table-hover table-striped">
										<tbody >
											{% for key, v in ability_dict.items %}
											<tr class="tr" title="{{v.detail}}" name="-,-,-,-,-,-,-">
												<td class="rank">{{key}}</td>
												<td class="name">{{v.name}}</td>
												<td class="ratio">{{v.usageRate|floatformat:-1}}%</td>
											</tr>
											{% empty %}
												There is no data to display
											{% endfor %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title" data-toggle="collapse" data-parent="#panel-1" href="#panel-element-3"><b>Nature</b></a>
							</div>
							<div id="panel-element-3" class="panel-collapse collapse">
								<div class="panel-body">
									<table class="table-hover table-striped">
										<tbody>
											{% for key, v in nature_dict.items %}
											<tr class="tr" title="{{v.detail}}" name="-,-,-,-,-,-,-">
												<td class="rank">{{key}}</td>
												<td class="name">{{v.name}}</td>
												<td class="ratio">{{v.usageRate|floatformat:-1}}%</td>
											</tr>
											{% empty %}
												There is no data to display
											{% endfor %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title" data-toggle="collapse" data-parent="#panel-1" href="#panel-element-4"><b>Held Item</b></a>
							</div>
							<div id="panel-element-4" class="panel-collapse collapse">
								<div class="panel-body">
									<table class="table-hover table-striped`">
										<tbody>
											{% for key, v in item_dict.items %}
											<tr class="tr" title="{{v.detail}}" name="-,-,-,-,-,-,-">
												<td class="rank">{{key}}</td>
												<td class="name">{{v.name}}</td>
												<td class="ratio">{{v.usageRate|floatformat:-1}}%</td>
											</tr>
											{% empty %}
												There is no data to display
											{% endfor %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
						
				</div>

				<!-- 第二列 -->
				<div class="col-md-4 column">
					<div class="thumbnail">
						<h4><span class="label label-success" style="position: absolute;left:2;top:0;">{{poke_now.ranking}}</span></h4>
						<img src="/static/poke/img/pgl/{{p_id}}.png">
					</div>
					<div class="row">
						<h3 style="width:200px; margin: auto;" id="{{p_id}},{{typeid}},{{seasonid}}" name="{{poke_now.name}}"><a href="{% url 'poke:index' pokemodel.id %}" target="_blank">{{poke_now.name}}</a>&emsp;{{poke_now.monsno}}</h3>
					</div>
					<div class="row" style="width:120px; margin: auto;">
						<div class="col-md-6">
							<h3><span class="label label-default" style="background-color: {{type1.color}}">{{type1.name}}</span></h3>
						</div>
						{% if type2 %}
						<div class="col-md-6">
							<h3><span class="label label-default" style="background-color: {{type2.color}}">{{type2.name}}</span></h3>
						</div>
						{% endif %}
					</div>
					<hr />
					<div class="prevnext">
						<div class="col-md-3"><button type="button" class="btn btn-sm btn-info" id="{{pokeInfo.beforePokemonId}},{{typeid}},{{seasonid}}">Prev</button></div>
						<div class="col-md-5">
							<select name="poke" id="pokeselect" onchange="" style="width:100px">
					      		<!-- <option value="">--精灵--</option> -->
					      		{% for key, v in allpoke_dict.items %}
								<option value="{{key}},{{typeid}},{{seasonid}}" name="{{key}}">{{v.name}}</option>
								{% endfor %}
							</select>
						</div>
						<div class="col-md-1"><button type="button" class="btn btn-sm btn-info" id="{{pokeInfo.nextPokemonId}},{{typeid}},{{seasonid}}">Next</button></div>
					</div>
				</div>

				<!-- 第三列 -->
				<div class="col-md-4 column">
					<h4 ><b id="name">技能</b></h4>
					<table class="table-hover table-striped" style="width:250px;">
						<thead>
					    	<tr>
					    		<th>属性</th>
					    		<th>类型</th>
					      		<th>威力</th>
					      		<th>命中</th>
					      		<th>先制</th>
					    	</tr>
					    </thead>
						<tbody>
							<tr>
								<td style="width:50px;"><span id="t1" class="label label-default"></span></td>
								<td style="width:50px;"><span id="t2" class="label label-default"></span></td>
								<td style="width:50px;" id="t3"></td>
								<td style="width:50px;" id="t4"></td>
								<td style="width:50px;" id="t5"></td>
							</tr>
						</tbody>
					</table>
					<hr />
					<p id="detail">说明</p>
					<hr />
					<div class="panel-group" id="panel-2">
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title" data-toggle="collapse" data-parent="#panel-2" href="#panel-element-5"><b>种族值</b>&emsp;<b>{{total}}</b></a>
							</div> 
							<div id="panel-element-5" class="panel-collapse collapse in">
								<div class="panel-body">
									<table class="table table-condensed">
										<tbody>
											{% for key, value in abili.items %}
											<tr>
												<td style="width:60px"><b>{{key|capfirst}}</b></td>
												<td style="width:50px">{{value}}</td>
												<td><div style="width:{{value}}px;height: 10px;background: rgb(100,{{value}},0); "></div></td>
											</tr>
											{% endfor %}
										</tbody>
									</table>
								</div>
							</div>
						</div>
						<div class="panel panel-default">
							<div class="panel-heading">
								 <a class="panel-title" data-toggle="collapse" data-parent="#panel-2" href="#panel-element-6"><b>特性</b></a>
							</div>
							<div id="panel-element-6" class="panel-collapse collapse">
								<div class="panel-body">
									<table class="table table-condensed">
										<thead>
										    <tr>
										      <th>一般特性</th>
										      <th>说明</th>
										    </tr>
										</thead>
										<tbody>
										    <tr>
										      <td style="width:80px">{{pokemodel.ability1.name}}</td>
										      <td>{{pokemodel.ability1.detail}}</td>
										    </tr>
										    {% ifnotequal pokemodel.ability2.name '无' %}
										    <tr>
										      <td style="width:80px">{{pokemodel.ability2.name}}</td>
										      <td>{{pokemodel.ability2.detail}}</td>
										    </tr>
										    {% endifnotequal %}
										</tbody>
									</table>
									<table class="table table-condensed">
										 <thead>
										    <tr>
										    	<th>隐藏特性</th>
										        <th>说明</th>
										    </tr>
										</thead>
										<tbody>
										    <tr>
										        <td style="width:80px">{{pokemodel.ability3.name}}</td>
										        <td>{{pokemodel.ability3.detail}}</td>
										    </tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>

		</div>
	</div>
</div>




